"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_boundary_hint.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _boundary_hint


@pytest.mark.detective
def test__boundary_hint_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _boundary_hint(diff_summary="abc", param_names=("x",))
    assert result is None


@pytest.mark.detective
def test__boundary_hint_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _boundary_hint(
        diff_summary="- \\n+ 1 <= x <= 3\n- 1 <= x <= 3\n- 1 <= x <= 3", param_names="x"
    )
    assert result is None
