"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_params_only.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _params_only


@pytest.mark.detective
def test__params_only_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _params_only(left="abc", right="abc", param_names=("x",))
    assert result is False


@pytest.mark.detective
def test__params_only_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _params_only(left="", right="", param_names=("x",))
    assert result is False


@pytest.mark.detective
def test__params_only_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _params_only(left="x", right="y", param_names="('x', 'y')")
    assert result is True
