"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_may_divert.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest

from uroboros.nextstep import _may_divert


@pytest.mark.detective
def test__may_divert_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _may_divert(
        node=ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ).body[0]
    )
    assert result is False


@pytest.mark.detective
def test__may_divert_value_1():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'str' object has no attribute '_fields') (confidence 0.95)."""
    try:
        _result = _may_divert(node="Return()")
    except AttributeError as _exc:
        assert str(_exc) == "'str' object has no attribute '_fields'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")
