"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::derive_next_step.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import derive_next_step


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({},), {"kind": "author", "items": [], "total": 0}),
        (
            (
                {
                    "survivor_report": {
                        "verdicts": [
                            {
                                "killable": False,
                                "crash_only": False,
                                "diff_summary": "boundary: internal hint",
                            },
                            {
                                "killable": False,
                                "crash_only": False,
                                "diff_summary": "boundary: external hint",
                            },
                        ]
                    },
                    "param_names": ["x", "y"],
                },
            ),
            {"kind": "author", "items": [], "total": 0},
        ),
    ],
)
def test_derive_next_step_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert derive_next_step(*args) == expected


@pytest.mark.detective
def test_derive_next_step_value_0():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'str' object has no attribute 'get') (confidence 0.95)."""
    try:
        _result = derive_next_step(
            state={
                "survivor_report": {
                    "verdicts": [
                        {"killable": True, "witness": "tuple('a', 'b')"},
                        {
                            "killable": False,
                            "crash_only": False,
                            "diff_summary": "minor change",
                        },
                    ]
                },
                "param_names": ["x", "y"],
            }
        )
    except AttributeError as _exc:
        assert str(_exc) == "'str' object has no attribute 'get'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")
