"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_comparisons.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _comparisons


@pytest.mark.detective
def test__comparisons_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _comparisons(src="abc")
    assert result == []


@pytest.mark.detective
def test__comparisons_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _comparisons(src="elif x == y:")
    assert repr(result) == "[('x', <class 'ast.Eq'>, 'y')]"


@pytest.mark.detective
def test__comparisons_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _comparisons(src="if x == y:")
    assert repr(result) == "[('x', <class 'ast.Eq'>, 'y')]"


@pytest.mark.detective
def test__comparisons_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _comparisons(src="if x == 5: \\n    pass")
    assert result == []
