"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_hint_relation.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _hint_relation


@pytest.mark.detective
def test__hint_relation_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _hint_relation(hint="abc")
    assert result == "abc"
