"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_difference_region.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _difference_region


@pytest.mark.detective
def test__difference_region_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _difference_region(op=1, m_op=1, left="abc", right="abc")
    assert result is None
