"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_line_gap_items.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _line_gap_items


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({},), []),
        (
            ({"missing_lines": [229], "missing_line_guards": {}},),
            ["line 229 — reach it"],
        ),
    ],
)
def test__line_gap_items_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _line_gap_items(*args) == expected
