"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_probe_python.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _probe_python


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["detective"],), ["python"]),
        ((["/x/.venv/bin/detective"],), ["/x/.venv/bin/python"]),
        ((["python"],), ["python", "python"]),
    ],
)
def test__probe_python_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _probe_python(*args) == expected
