"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_functions_in_ranges.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _functions_in_ranges


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", [1]), []),
        (("def f1(): pass\ndef f2(): pass\n", [[1, 1], [2, 2]]), ["f1", "f2"]),
        (("def f1(): pass\ndef f2(): pass\n", [[1, 5], [6, 10]]), ["f1", "f2"]),
        (("def __init__(): pass\ndef f1(): pass\n", [[1, 1], [1, 1]]), []),
        (("def f1(): pass\n", [[1, 0], [2, 3]]), []),
    ],
)
def test__functions_in_ranges_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert _functions_in_ranges(*args) == expected


@pytest.mark.detective
def test__functions_in_ranges_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _functions_in_ranges(source="def f(): pass\ndef", ranges=[[0, 0]])
    assert result == []
