"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_always_evaluated.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _always_evaluated


@pytest.mark.detective
def test__always_evaluated_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _always_evaluated(orig_src="abc", left="abc", op=1, right="abc")
    assert result is False


@pytest.mark.detective
def test__always_evaluated_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _always_evaluated(orig_src="", left="", op=-1, right="")
    assert result is False


@pytest.mark.detective
def test__always_evaluated_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _always_evaluated(
        orig_src="def f():\n    x = 5\n    if x < 10:\n        pass\n    return x > 5",
        left="x",
        op="lt",
        right="10",
    )
    assert result is False
