"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_dotted_module.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _dotted_module


@pytest.mark.detective
def test__dotted_module_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _dotted_module(sample_file="/a/b/c/mod.py", roots=["/a", "/a/b"])
    assert result == ("/a/b", "c.mod")


@pytest.mark.detective
def test__dotted_module_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _dotted_module(sample_file="/x/y.py", roots=["/a", "/b"])
    assert result is None


@pytest.mark.detective
def test__dotted_module_value_2():
    """VALUE survivor — distinguishing witness (original raises TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'int') (confidence 0.95)."""
    try:
        _result = _dotted_module(sample_file=-1, roots=-1)
    except TypeError as _exc:
        assert (
            str(_exc)
            == "argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'int'"
        )
    except BaseException as _exc:
        pytest.fail(f"expected TypeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected TypeError, but the call returned {_result!r}")
