"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_differs_at_eq.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.nextstep import _differs_at_eq


@pytest.mark.detective
def test__differs_at_eq_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _differs_at_eq(op=1, m_op=1)
    assert result is False
