"""Auto-generated by Detective — warrant-classed tests for uroboros/nextstep.py::_predecessors_fall_through.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest

from uroboros.nextstep import _predecessors_fall_through


@pytest.mark.detective
def test__predecessors_fall_through_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _predecessors_fall_through(
        parent=ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ).body[0],
        child=ast.parse("total = abs(total)").body[0],
    )
    assert result is True
