"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_changed_line_ranges.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _changed_line_ranges


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), {}),
        (
            (
                "+++ b/file1.py\n@@ -1,3 +1,4 @@\n- print('old')\n+ print('old')\n+ print('new')",
            ),
            {"file1.py": [(1, 4)]},
        ),
        (("+++ b/file2.py\n@@ -1,1 +1,0 @@\n- print('line')",), {}),
        (("+++ b/file4.py\n@@ -1,0 +1,1 @@\n+ new_line",), {"file4.py": [(1, 1)]}),
    ],
)
def test__changed_line_ranges_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert _changed_line_ranges(*args) == expected
