"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_lint_regressed.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _lint_regressed


@pytest.mark.detective
def test__lint_regressed_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _lint_regressed(before=None, after=5)
    assert result is False


@pytest.mark.detective
def test__lint_regressed_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _lint_regressed(before=5, after=None)
    assert result is False


@pytest.mark.detective
def test__lint_regressed_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _lint_regressed(before=2, after=5)
    assert result is True


@pytest.mark.detective
def test__lint_regressed_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _lint_regressed(before=5, after=2)
    assert result is False


@pytest.mark.detective
def test__lint_regressed_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _lint_regressed(before=3, after=3)
    assert result is False
