"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_engine_prefix.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _engine_prefix


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2, 3, 4, 5), ([3], None, False)),
        (
            ("/r", "/uv", None, None, True),
            (
                ["/uv", "run", "--no-sync", "--with", "detective-spec", "detective"],
                "/r",
                False,
            ),
        ),
        (("/r", None, None, None, True), (["detective"], None, True)),
    ],
)
def test__engine_prefix_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _engine_prefix(*args) == expected


@pytest.mark.detective
def test__engine_prefix_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _engine_prefix(root=1, uv=3, active=0, venv=2, isolated=-1)
    assert result == ([2], None, False)


@pytest.mark.detective
def test__engine_prefix_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _engine_prefix(root=0, uv=0, active=0, venv=0, isolated=0)
    assert result == (["detective"], None, False)
