"""Auto-generated by Detective — warrant-classed tests for uroboros/drive.py::_new_tracked_writes.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.drive import _new_tracked_writes


@pytest.mark.detective
def test__new_tracked_writes_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _new_tracked_writes(
        before=["keep.py"],
        after=[
            "keep.py",
            "tests/x.py",
            "data/f.json",
            ".detective/r.txt",
            "a/__pycache__/x.pyc",
            "session_universe/",
        ],
    )
    assert result == ["data/f.json", "session_universe/"]
