"""Auto-generated by Detective — warrant-classed tests for uroboros/launch.py::_launch_argv.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from uroboros.launch import _launch_argv


@pytest.mark.detective
def test__launch_argv_swap_0():
    """SWAP survivor [SWAP_350cd0c5] — root != apply; non-commutative (confidence 0.6)."""
    result_ab = _launch_argv(1, 2)
    result_ba = _launch_argv(2, 1)
    assert result_ab != result_ba, "SWAP: parameter order should matter"


@pytest.mark.detective
def test__launch_argv_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _launch_argv(root=1, apply=True)
    assert result == ["uroboros", ".", "--apply", "--project-root", "1"]
